name: ColoredChat
main: com.cyber.coloredChat.ColoredChat
version: ${project.version}
authors:
    - CyberDrain
description: Adds colors to the chat
commands:
    colors:
        description: Basic command
        aliases: [colours]